
package br.com.treino.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ExameServiceImpService", targetNamespace = "http://soap.treino.com.br/", wsdlLocation = "http://localhost:8080/okami/soap?wsdl")
public class ExameServiceImpService
    extends Service
{

    private final static URL EXAMESERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXAMESERVICEIMPSERVICE_EXCEPTION;
    private final static QName EXAMESERVICEIMPSERVICE_QNAME = new QName("http://soap.treino.com.br/", "ExameServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/okami/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMESERVICEIMPSERVICE_WSDL_LOCATION = url;
        EXAMESERVICEIMPSERVICE_EXCEPTION = e;
    }

    public ExameServiceImpService() {
        super(__getWsdlLocation(), EXAMESERVICEIMPSERVICE_QNAME);
    }

    public ExameServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMESERVICEIMPSERVICE_QNAME, features);
    }

    public ExameServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, EXAMESERVICEIMPSERVICE_QNAME);
    }

    public ExameServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMESERVICEIMPSERVICE_QNAME, features);
    }

    public ExameServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExameServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExameService
     */
    @WebEndpoint(name = "ExameServiceImpPort")
    public ExameService getExameServiceImpPort() {
        return super.getPort(new QName("http://soap.treino.com.br/", "ExameServiceImpPort"), ExameService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExameService
     */
    @WebEndpoint(name = "ExameServiceImpPort")
    public ExameService getExameServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.treino.com.br/", "ExameServiceImpPort"), ExameService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMESERVICEIMPSERVICE_EXCEPTION!= null) {
            throw EXAMESERVICEIMPSERVICE_EXCEPTION;
        }
        return EXAMESERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
